### ISSUE TITLE
what's the final conclusion?

### ISSUE THREAD

**Issue by SoonyangZhang** [zamaniali1995/A-Reinforcement-Learning-Algorithm-for-Service-Function-Chain-SFC-Mapping#1]
what's your final conclusion by implmenting the idea in the origin paper? Do you think their method is better that other methods？

**Comment by hangones** [comment]
Hello, have you reproduced the author's paper? I have a few questions to ask. 1 The reward for the author's thesis is the ratio of revenue to cost,  in the simulation results, the ratio of income to expense is around 10,000, but the ratio of income to expense should not be less than 1. 2 How to explain the author's simulation revenue is larger than the cost?

**Comment by hangones** [comment]
Hello, have you reappearance of the author's paper? I have a few questions to ask. 1 The reward for the author's thesis is the ratio of revenue to cost, in the simulation results, the ratio of income to expense is around 10,000, but the ratio of income to expense should not be less than 1. 2 How to explain the author's simulation revenue is larger than the cost?

**Comment by hangones** [comment]
> what's your final conclusion by implmenting the idea in the origin paper? Do you think their method is better that other methods？

Hello, have you reappearance of the author's paper? I have a few questions to ask. 1 The reward for the author's thesis is the ratio of revenue to cost, in the simulation results, the ratio of income to expense is around 10,000, but the ratio of income to expense should not be less than 1. 2 How to explain the author's simulation revenue is larger than the cost?

**Comment by SoonyangZhang** [comment]
Sorry，I did not run the code here. And I am also not familiar with SFC.
